export const NEWS: { date: string; text: string }[] = [
  { date: '24 June 2026', text: 'Beta version of the new WXDA website launched' },
  { date: '22 October 2025', text: 'Work on revised fields and values continues' },
  { date: '14 January 2025', text: 'Implementation of revised fields and values is ongoing' },
  { date: '20 August 2024', text: 'Edits to improve inclusivity of the WXDA database’s fields and values have been completed' },
  { date: '26 July 2024', text: 'Some edits are currently underway to improve the inclusivity of the WXDA database’s fields and values' },
  { date: '17 January 2024', text: 'The stable, open access links to the PDFs for Times articles are functioning once again' },
  { date: '14 January 2024', text: 'The WXDA Advisory Board has been launched! (see the Advisory Board tab above); the Instructions tab has been updated' },
  { date: '10 January 2024', text: 'We’re aware that URL links to the PDFs of Times articles are malfunctioning; an enquiry is in with Cengage to arrange a fix' },
  { date: '31 December 2023', text: 'Coming soon: the WXDA Advisory Board' },
  { date: '21 October 2022', text: '1833 updated with 16 new records' },
  { date: '14 September 2022', text: 'Records for 1802 posted' },
  { date: '10 August 2022', text: 'Records for 1801 posted' },
  { date: '25 July 2022', text: 'Records for 1848 posted' },
]